POST http://localhost:3000/login/
Content-Type: application/json

{    
    "username": "christopher_phillips",
    "password": "christy@123"
}

###

GET http://localhost:3000/login/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjI4NDM1MzgyfQ.Vw95K_7LNroOCHPUT82RFy26H7272WzhgVcVLcHIUCw



####
GET http://localhost:3000/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjI4NDM1MzgyfQ.Vw95K_7LNroOCHPUT82RFy26H7272WzhgVcVLcHIUCw

###
GET http://localhost:3000/states/:stateId/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjI4NDM1MzgyfQ.Vw95K_7LNroOCHPUT82RFy26H7272WzhgVcVLcHIUCw

